/*
 * DazzleConf
 * Copyright © 2025 Anand Beh
 *
 * DazzleConf is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * DazzleConf is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with DazzleConf. If not, see <https://www.gnu.org/licenses/>
 * and navigate to version 3 of the GNU Lesser General Public License.
 */

package space.arim.dazzleconf2.backend;

import org.checkerframework.checker.nullness.qual.NonNull;

import java.io.IOException;
import java.util.Objects;

/**
 * A displayable item, printed in one of multiple ways.
 * <p>
 * No matter the printing method used, the content generated by each method must be the same result. For example,
 * the following assertion should pass:
 * <pre>
 *     {@code
 *     Printable printable = ...;
 *     StringBuilder builder = new StringBuilder();
 *     printable.printTo(builder);
 *     assert printable.printString().equals(builder.toString());
 *     }
 * </pre>
 */
public interface Printable {

    /**
     * Gets the printed content as a string
     *
     * @return printed string
     */
    @NonNull String printString();

    /**
     * Prints to the given appendable
     *
     * @param output where to place the message
     * @throws IOException if the output threw this error, it is propagated
     */
    void printTo(@NonNull Appendable output) throws IOException;

    /**
     * Prints to the given builder
     *
     * @param output where to place the message
     */
    void printTo(@NonNull StringBuilder output);

    /**
     * Gets a string representation.
     * <p>
     * Implementations are strongly encouraged (but not required) to return the same value as fo {@link #printString()}
     *
     * @return a string representation of this object
     */
    @Override
    String toString();

    /**
     * Makes a simple implementation based on an existing string. The argument will be yielded by each of the printing
     * methods.
     *
     * @param content the prebuilt string
     * @return a printable using it
     */
    static @NonNull Printable preBuilt(@NonNull CharSequence content) {
        Objects.requireNonNull(content);
        return new Printable() {
            @Override
            public @NonNull String printString() {
                return content.toString();
            }

            @Override
            public void printTo(@NonNull Appendable output) throws IOException {
                output.append(content);
            }

            @Override
            public void printTo(@NonNull StringBuilder output) {
                output.append(content);
            }

            @Override
            public String toString() {
                return printString();
            }
        };
    }
}
