name: Java CI

on:
  push:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8 for toolchain
      id: setup-java8
      uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: 'zulu'
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: 16
        distribution: 'zulu'
    - name: Build with Maven
      run: export JAVA8_HOME=${{ steps.setup-java8.outputs.path }} && mvn -B verify -Dgpg.skip=true --global-toolchains .github/workflows/toolchains.xml -Pgithub-workflow
