name: Java CI

on:
  push:
    branches: [ '*' ]
  pull_request:

jobs:
  build:
    # Credits to ViaVersion; this prevents the build from running twice
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Set up JDK 8 for toolchain
      id: setup-java8
      uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: 'zulu'
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'zulu'

    - name: Build with Maven
      run: export JAVA8_HOME=${{ steps.setup-java8.outputs.path }} && mvn -B verify -Dgpg.skip=true --global-toolchains .github/workflows/toolchains.xml -Pgithub-workflow
