name: Java CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: 16
        distribution: 'zulu'
        architecture: x64
    - name: Build with Maven
      run: mvn -B verify -Dgpg.skip=true
